### ISSUE TITLE
TypeError after fresh installation

### ISSUE THREAD

**Issue by philip-hartmann** [TYPO3-Headless/create-nuxt-typo3#5]
I get the TypeError `Cannot read property 'url' of undefined` after a fresh installation with the following choices made during the create process:
- npm
- javascript
- modules: nuxt-typo3, axios, pwa, dotenv
- universal (ssr) rendering mode

Tested with node version `14.5.0` and `8.9.0`.

**Comment by mercs600** [comment]
@philip-hartmann it looks like something wrong with connection to the API, can you show me your nuxt.config.js ?

**Comment by philip-hartmann** [comment]
```
export default {
  mode: 'universal',
  /*
  ** Headers of the page
  */
  head: {
    title: process.env.npm_package_name || '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: process.env.npm_package_description || '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#ff8700' },
  /*
  ** Global CSS
  */
  css: [
  ],
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
  ],
  /*
  ** Nuxt.js dev-modules
  */
  buildModules: [
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    // Doc: https://github.com/mercs600/nuxt-typo3-skin
    'nuxt-typo3-skin',
    // Doc: https://github.com/TYPO3-Initiatives/nuxt-typo3
    'nuxt-typo3',
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
      // Doc: https://github.com/nuxt-community/dotenv-module
    '@nuxtjs/dotenv'
  ],
  /*
  ** TYPO3 module configuration
  ** https://github.com/TYPO3-Initiatives/nuxt-typo3
  */
  typo3: {
    baseURL: process.env.NUXT_HOST,
    api: {
      baseURL: 'https://typo3.docker.localhost'
    },
  },
  /*
  ** Axios module configuration
  ** See https://axios.nuxtjs.org/options
  */
  axios: {
  },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
    }
  }
}
```

The `Access-Control-Allow-Origin` header is set for all origins for the api. The api does not receive any requests at that point, nor does the client send any.

**Comment by mercs600** [comment]
@philip-hartmann check these solutions:
1. Remove  `@nuxtjs/axios`, from`modules`- because we are loading Axios inside of our module and I saw some issues with that - we have to fix. 
2. Please use for test our demo api `https://api.t3pwa.com` and check is it works? - If yes, there is some issue with your API. Important thing when you try to connect from SSR(node) context to local https - you have to have full secure certificate. If you haven't please get familiar with this global variable -> `NODE_TLS_REJECT_UNAUTHORIZED=0` -> this is helpful and disable some policies with secure of certs - but it doesn't fit for production ;-)

**Comment by philip-hartmann** [comment]
Setting `NODE_TLS_REJECT_UNAUTHORIZED=0` in the `.env` file worked wonders. Thanks!
